export const fruits = [
    { name: "oranges", desc: "Vitamin C" },
    { name: "apples", desc: "Vitamin C" },
    { name: "avocados", desc: "Vitamin B6" },
    { name: "strawberries", desc: "Vitamin C" },
    { name: "mangoes", desc: "Vitamin A, C" },
    { name: "blueberries", desc: "Vitamin C, K" },
    { name: "grapse", desc: "Vitamin C, K" },
    { name: "pineapples", desc: "Vitamin C, K" },
    { name: "papayas", desc: "Vitamin C" },
    { name: "oranges", desc: "Vitamin C" },
    { name: "apples", desc: "Vitamin C" },
    { name: "avocados", desc: "Vitamin B6" },
    { name: "strawberries", desc: "Vitamin C" },
    { name: "mangoes", desc: "Vitamin A, C" },
    { name: "blueberries", desc: "Vitamin C, K" },
    { name: "grapse", desc: "Vitamin C, K" },
    { name: "pineapples", desc: "Vitamin C, K" },
    { name: "papayas", desc: "Vitamin C" },
  ];
 export const vegs = [
    { name: "carrot", desc: "Vitamin C" },
    { name: "broccoli", desc: "Vitamin B6" },
    { name: "spinach", desc: "Vitamin C" },
    { name: "tomatos", desc: "Vitamin C" },
    { name: "bell Peppers", desc: "Vitamin A, C" },
    { name: "onions", desc: "Vitamin C, K" },
    { name: "zuchinni", desc: "Vitamin C, K" },
    { name: "cucumbers", desc: "Vitamin C, K" },
    { name: "potatos", desc: "Vitamin C" },
    { name: "carrot", desc: "Vitamin C" },
    { name: "broccoli", desc: "Vitamin B6" },
    { name: "spinach", desc: "Vitamin C" },
    { name: "tomatos", desc: "Vitamin C" },
    { name: "bell Peppers", desc: "Vitamin A, C" },
    { name: "onions", desc: "Vitamin C, K" },
    { name: "zuchinni", desc: "Vitamin C, K" },
    { name: "cucumbers", desc: "Vitamin C, K" },
    { name: "potatos", desc: "Vitamin C" },

  ];
